### ISSUE TITLE
Install sim-module on raspberry

### ISSUE THREAD

**Issue by heximcz** [JFF-Bohdan/sim-module#1]
Hello,

I have problem with install on Raspbeerry Pi:

root@raspberrypi:~# pip install https://github.com/JFF-Bohdan/sim-module/archive/master.zip
Downloading/unpacking https://github.com/JFF-Bohdan/sim-module/archive/master.zip
  Downloading master.zip
  Running setup.py egg_info for package from https://github.com/JFF-Bohdan/sim-module/archive/master.zip
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-fQkan7-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-fQkan7-build/setup.py'

---

Command python setup.py egg_info failed with error code 1 in /tmp/pip-fQkan7-build
Storing complete log in /root/.pip/pip.log

Please tell me how install this library correctly ?

Thank you and Best regards

**Comment by JFF-Bohdan** [comment]
Hello. Sorry, but there is no "setup.py" in my package. You can just
download/unpack and start using by test examples. Also, you may need to
tune up tty address.

On Fri, Aug 21, 2015 at 5:03 PM, heximcz notifications@github.com wrote:

> Hello,
> 
> I have problem with install on Raspbeerry Pi:
> 
> root@raspberrypi:~# pip install
> https://github.com/JFF-Bohdan/sim-module/archive/master.zip
> Downloading/unpacking
> https://github.com/JFF-Bohdan/sim-module/archive/master.zip
> Downloading master.zip
> Running setup.py egg_info for package from
> https://github.com/JFF-Bohdan/sim-module/archive/master.zip
> Traceback (most recent call last):
> File "", line 14, in
> IOError: [Errno 2] No such file or directory:
> '/tmp/pip-fQkan7-build/setup.py'
> Complete output from command python setup.py egg_info:
> Traceback (most recent call last):
> 
> File "", line 14, in
> 
> IOError: [Errno 2] No such file or directory:
> 
> ## '/tmp/pip-fQkan7-build/setup.py'
> 
> Command python setup.py egg_info failed with error code 1 in
> /tmp/pip-fQkan7-build
> Storing complete log in /root/.pip/pip.log
> 
> Please tell me how install this library correctly ?
> 
> Thank you and Best regards
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JFF-Bohdan/sim-module/issues/1.

## 

Best Regards,

Bohdan Danishevsky
Aminis LLC, CEO

+38-067-509-15-23
http://www.aminis.com.ua

**Comment by heximcz** [comment]
Ok, thank you. But when I run test_basic_class.py script, I get this error:

root@raspberrypi:~/sim-module# ./test_basic_class.py 
Traceback (most recent call last):
  File "./test_basic_class.py", line 4, in <module>
    from test_shared import initializeUartPort, initializeLogs
  File "/root/sim-module/test_shared.py", line 4, in <module>
    from lib.sim900.gsm import SimGsm, SimGsmPinRequestState
  File "/root/sim-module/lib/sim900/gsm.py", line 114
    def print(self, commandString, encoding = "ascii"):
            ^
SyntaxError: invalid syntax

another test script show this error:

root@raspberrypi:~/sim-module# ./test_http.py 
from: can't read /var/mail/test_shared
from: can't read /var/mail/lib.sim900.inetgsm
./test_http.py: line 4: COMPORT_NAME: command not found
./test_http.py: line 7: CONSOLE_LOGGER_LEVEL: command not found
./test_http.py: line 8: LOGGER_LEVEL: command not found
./test_http.py: line 10: syntax error near unexpected token `('
./test_http.py: line 10:`def main():'

Thank you.

**Comment by JFF-Bohdan** [comment]
Ok, that's interesting. I will look for this issue at this night. After 24
h I will send you my answer. Thank you.

On Fri, Aug 21, 2015 at 5:17 PM, heximcz notifications@github.com wrote:

> Ok, thank you. But when I run test_basic_class.py script, I get this error:
> 
> root@raspberrypi:~/sim-module# ./test_basic_class.py
> Traceback (most recent call last):
> File "./test_basic_class.py", line 4, in
> from test_shared import initializeUartPort, initializeLogs
> File "/root/sim-module/test_shared.py", line 4, in
> from lib.sim900.gsm import SimGsm, SimGsmPinRequestState
> File "/root/sim-module/lib/sim900/gsm.py", line 114
> def print(self, commandString, encoding = "ascii"):
> ^
> SyntaxError: invalid syntax
> 
> another test script show this error:
> 
> root@raspberrypi:~/sim-module# ./test_http.py
> from: can't read /var/mail/test_shared
> from: can't read /var/mail/lib.sim900.inetgsm
> ./test_http.py: line 4: COMPORT_NAME: command not found
> ./test_http.py: line 7: CONSOLE_LOGGER_LEVEL: command not found
> ./test_http.py: line 8: LOGGER_LEVEL: command not found
> ./test_http.py: line 10: syntax error near unexpected token ('
> ./test_http.py: line 10:def main():'
> 
> Thank you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JFF-Bohdan/sim-module/issues/1#issuecomment-133439836
> .

## 

Best Regards,

Bohdan Danishevsky
Aminis LLC, CEO

+38-067-509-15-23
http://www.aminis.com.ua

**Comment by JFF-Bohdan** [comment]
Ok. Now I can see. You trying to execute test_\* files as bash scripts, but
they are Python files and must be executed via Python interpreter.

Also, you need tune up com port (tty) name. You can't just run test in this
way.

I need to write a little portion of instructions to you, is't it?

On Fri, Aug 21, 2015 at 5:17 PM, heximcz notifications@github.com wrote:

> Ok, thank you. But when I run test_basic_class.py script, I get this error:
> 
> root@raspberrypi:~/sim-module# ./test_basic_class.py
> Traceback (most recent call last):
> File "./test_basic_class.py", line 4, in
> from test_shared import initializeUartPort, initializeLogs
> File "/root/sim-module/test_shared.py", line 4, in
> from lib.sim900.gsm import SimGsm, SimGsmPinRequestState
> File "/root/sim-module/lib/sim900/gsm.py", line 114
> def print(self, commandString, encoding = "ascii"):
> ^
> SyntaxError: invalid syntax
> 
> another test script show this error:
> 
> root@raspberrypi:~/sim-module# ./test_http.py
> from: can't read /var/mail/test_shared
> from: can't read /var/mail/lib.sim900.inetgsm
> ./test_http.py: line 4: COMPORT_NAME: command not found
> ./test_http.py: line 7: CONSOLE_LOGGER_LEVEL: command not found
> ./test_http.py: line 8: LOGGER_LEVEL: command not found
> ./test_http.py: line 10: syntax error near unexpected token ('
> ./test_http.py: line 10:def main():'
> 
> Thank you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JFF-Bohdan/sim-module/issues/1#issuecomment-133439836
> .

## 

Best Regards,

Bohdan Danishevsky
Aminis LLC, CEO

+38-067-509-15-23
http://www.aminis.com.ua

**Comment by JFF-Bohdan** [comment]
Can we talk in Skype? Will it be comfortable to you?

On Fri, Aug 21, 2015 at 7:43 PM, Bohdan Danishevsky dbn@aminis.com.ua
wrote:

> Ok. Now I can see. You trying to execute test_\* files as bash scripts, but
> they are Python files and must be executed via Python interpreter.
> 
> Also, you need tune up com port (tty) name. You can't just run test in
> this way.
> 
> I need to write a little portion of instructions to you, is't it?
> 
> On Fri, Aug 21, 2015 at 5:17 PM, heximcz notifications@github.com wrote:
> 
> > Ok, thank you. But when I run test_basic_class.py script, I get this
> > error:
> > 
> > root@raspberrypi:~/sim-module# ./test_basic_class.py
> > Traceback (most recent call last):
> > File "./test_basic_class.py", line 4, in
> > from test_shared import initializeUartPort, initializeLogs
> > File "/root/sim-module/test_shared.py", line 4, in
> > from lib.sim900.gsm import SimGsm, SimGsmPinRequestState
> > File "/root/sim-module/lib/sim900/gsm.py", line 114
> > def print(self, commandString, encoding = "ascii"):
> > ^
> > SyntaxError: invalid syntax
> > 
> > another test script show this error:
> > 
> > root@raspberrypi:~/sim-module# ./test_http.py
> > from: can't read /var/mail/test_shared
> > from: can't read /var/mail/lib.sim900.inetgsm
> > ./test_http.py: line 4: COMPORT_NAME: command not found
> > ./test_http.py: line 7: CONSOLE_LOGGER_LEVEL: command not found
> > ./test_http.py: line 8: LOGGER_LEVEL: command not found
> > ./test_http.py: line 10: syntax error near unexpected token ('
> > ./test_http.py: line 10:def main():'
> > 
> > Thank you.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/JFF-Bohdan/sim-module/issues/1#issuecomment-133439836
> > .
> 
> ## 
> 
> Best Regards,
> 
> Bohdan Danishevsky
> Aminis LLC, CEO
> 
> +38-067-509-15-23
> http://www.aminis.com.ua

## 

Best Regards,

Bohdan Danishevsky
Aminis LLC, CEO

+38-067-509-15-23
http://www.aminis.com.ua

**Comment by heximcz** [comment]
Little guidance would certainly help, thank you.
Sorry but I do not have skype.

**Comment by heximcz** [comment]
Problem was been with python version, when I use Python version > 3, script work ok, but

**Comment by heximcz** [comment]
Problem have been with python version :-), after I use Python version > 3.x, script work ok. I have port ttyAMA0 but I still get this error:

root@raspberrypi:~/sim-module# python3.2 ./test_basic_class.py 
[2015-08-23 23:01:35,220] INFO: opening port
[2015-08-23 23:01:35,224] ERROR: exception till port openning: could not open port ttyAMA0: [Errno 2] No such file or directory: 'ttyAMA0'
[2015-08-23 23:01:35,228] ERROR: error opening port: exception till port openning: could not open port ttyAMA0: [Errno 2] No such file or directory: 'ttyAMA0'
DONE

default port com22 not work too. 
Please tell me how I set right port ? 

Thank you and best regards!

**Comment by heximcz** [comment]
Problem solved, 

COMPORT_NAME            = "/dev/ttyAMA0"

:-D Thank you !

**Comment by JFF-Bohdan** [comment]
Yes, you need specify UART name for your SIM-module. Also, may be needful
to specify UART speed, parity and other parameters.
