### ISSUE TITLE
timeDelta function returns wrong time delta

### ISSUE THREAD

**Issue by Vangeels** [JFF-Bohdan/sim-module#11]
Is there a specific reason to return twice the amount of time (return secs*1000 + msecs)?

def timeDelta(timeBegin):
    end     = time.time()
    secs    = end - timeBegin
    msecs   = (end - timeBegin) * 1000.0

    return secs*1000 + msecs

**Comment by JFF-Bohdan** [comment]
Hello,

It not a feature, it's just a bug. It's very old code, I not write in this way now. Sorry. Thank you for your report.

**Comment by Vangeels** [comment]
Hi Bohdan,


No thank you for your code. And thanks for your reply.


Have a nice day.


Best regards.

________________________________
